image: pksadiq/gtk:fedora-amd64

stages:
  - build
  - test
  - deploy

build-gtk3:
  stage: build
  variables:
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - ./new-project.sh gtk3
    - cd gee-tasks
    - meson ${MESON_ARGS} -Db_coverage=true _build
    - ninja -C _build

build:
  stage: build
  variables:
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - meson ${MESON_ARGS} -Db_coverage=true _build
    - meson test -C _build
    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    paths:
      - _build

pages:
  image: alpine:3.8
  stage: deploy
  script:
    - mkdir public
    - mv _build/meson-logs/coveragereport ${CI_PROJECT_DIR}/public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
