stages:
  - build
  - test
  - deploy

build-gtk3:
  image: pksadiq/gtk:alpine-amd64
  stage: build
  variables:
    CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
    CCACHE_DIR: "${CCACHE_BASEDIR}/_ccache-gtk3"
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - ./new-project.sh gtk3
    - cd gee-tasks
    - ccache --zero-stats
    - meson ${MESON_ARGS} -Db_coverage=true _build
    - ninja -C _build
    - ccache --show-stats
  cache:
    key: build-gtk3
    paths:
      - _ccache-gtk3/

build:
  image: pksadiq/gtk:fedora-amd64
  stage: build
  variables:
    CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
    CCACHE_DIR: "${CCACHE_BASEDIR}/_ccache-gtk4"
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - ccache --zero-stats
    - meson ${MESON_ARGS} -Db_coverage=true _build
    - meson test -C _build
    - ccache --show-stats
    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  cache:
    key: build-gtk4
    paths:
      - _ccache-gtk4/
  artifacts:
    when: always
    paths:
      - _build

pages:
  image: busybox:1
  stage: deploy
  script:
    - mkdir public
    - mv _build/meson-logs/coveragereport ${CI_PROJECT_DIR}/public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
