stages:
  - build
  - test
  - deploy

build:
  image: pksadiq/gtk:fedora-amd64
  stage: build
  variables:
    CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
    CCACHE_DIR: "${CCACHE_BASEDIR}/_ccache-gtk4"
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - meson ${MESON_ARGS} -Db_coverage=true _build
    - ccache --zero-stats
    - meson test -C _build
    - ccache --show-stats
    - mkdir -p _build/meson-logs/coveragereport
    - gcovr --root=_build --html-details --print-summary
      --filter=. --exclude=.*gtkapplication.h --exclude=.*src/resources.c --exclude=.*autocleanups.h
      -o _build/meson-logs/coveragereport/index.html
  coverage: '/^lines:.*\s+(\S+\%).*$/'
  cache:
    key: build-gtk4
    paths:
      - _ccache-gtk4/
  artifacts:
    when: always
    paths:
      - _build

pages:
  image: busybox:1
  stage: deploy
  script:
    - mkdir public
    - mv _build/meson-logs/coveragereport ${CI_PROJECT_DIR}/public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
