stages:
  - build
  - test

build:
  image: pksadiq/gtk:alpine-amd64
  stage: build
  variables:
    MESON_ARGS: "--buildtype=debugoptimized -Dhelp=true -Dgtk_doc=true -Dtracing=true"
  script:
    - ./new-project.sh gtk3
    - cd gee-tasks
    - meson ${MESON_ARGS} _build
    - ninja -C _build
    - cd ..
  artifacts:
    name: "app-${CI_COMMIT_REF_NAME}"
    paths:
      - gee-tasks

test:
  image: pksadiq/gtk:alpine-amd64
  stage: test
  script:
    - cd gee-tasks
    - meson test -C _build
